minimum_pre_commit_version: 2.10.0

repos:
  - repo: 'https://github.com/psf/black'
    rev: 20.8b1
    hooks:
      - id: black
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.4.0
    hooks:
      - id: check-symlinks
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-toml
      - id: check-json
      - id: check-yaml
