# SPDX-FileCopyrightText: Copyright 2020-2023, Contributors to typed-dfs
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/typed-dfs
# SPDX-License-Identifier: Apache-2.0

# Check out https://pre-commit.com/ for documentation
minimum_pre_commit_version: 3.3.3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
        exclude: ^recipes/.*
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      - id: trailing-whitespace

  # --- Commit msg checks ---
  - hooks:
      - id: commitizen
        stages: ["commit-msg"]
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.6.0

  # --- Linters ---
  #- repo: https://github.com/astral-sh/ruff-pre-commit
  #  rev: v0.1.1
  #  hooks:
  #    - id: ruff
  #      args: [--fix]
  #      fail_fast: false
  #      types_or: [python, pyi, jupyter]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.14.0
    hooks:
      - id: blacken-docs

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        stages: [commit]
        # :tyranno: [--print-width, "${tool.ruff.line-length}"]
        args: [--print-width, "100"]
        exclude: ^recipes/.*

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.9.0
    hooks:
      - id: pretty-format-ini
        args: [--autofix]
